//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WITH_MULTIPLE_CONTROL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.SelectedHobbyOfEmployeeWises = new HashSet<SelectedHobbyOfEmployeeWise>();
        }
    
        public int EmpId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public int GenderId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FilePath { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<SelectedHobbyOfEmployeeWise> SelectedHobbyOfEmployeeWises { get; set; }
    }
}
